### ISSUE TITLE
Exception when casting an IITTrack to IITFileOrCDTrack

### ISSUE THREAD

**Issue by syroy** [rogerms/ITunesSDK#1]
Thanks for your bits of code, very helpful but I am encountering an issue trying to cast an IITTrack that is part of a shared library that does not seem to like being casted into an IITFileOrCDTrack in order to get the location. Would you have an idea how to fix that?

**Comment by syroy** [comment]
Thought this could help
![image](https://user-images.githubusercontent.com/33747986/109171205-899fb900-774f-11eb-9c36-89ea6feba1ff.png)

**Comment by rogerms** [comment]
I haven't played with this for a long time so I don't know if can help
at this point.
It is very possible that the problem is with just a few bad tracks and you
just need to skip them.
Check each track to make sure it is not NULL or something; before trying to
cast it.
A TRY?CATCH statement around it might solve the problem.
I hope this helps
Roger

**Comment by syroy** [comment]
Thanks for your reply. I found a workaround bu checking the track.Kind first. When == ITTrackKind.ITTrackKindFile everything is OK. It is just surprising that the AlbumArtist is not available when == ITTrackKind.ITTrackKindSharedLibrary! And Apple does not maintain nor take issues with the Windows SDK anymore...
